"""Initial migration

Revision ID: 6a0b8863e472
Revises: 
Create Date: 2024-11-05 22:36:21.183334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a0b8863e472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('answers_submitted', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_submitted_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index('ix_environments_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('form_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_form_answers_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('form_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_form_questions_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_form_submissions_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index('ix_forms_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_permissions_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.drop_index('ix_question_types_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_role_permissions_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_deleted')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_users_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_roles_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_role_permissions_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_questions_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('question_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_question_types_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_permissions_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_forms_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_form_submissions_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('form_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_form_questions_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('form_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_form_answers_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_environments_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_attachments_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('answers_submitted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_answers_submitted_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_index('ix_answers_is_deleted', ['is_deleted'], unique=False)

    # ### end Alembic commands ###
