"""Migration2

Revision ID: 6e9ca5aa36bb
Revises: 92abd632dcec
Create Date: 2024-10-29 20:41:37.682697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9ca5aa36bb'
down_revision = '92abd632dcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('form_submissions_question_answer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])
        batch_op.drop_column('question_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_answer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('form_submissions_question_answer_fkey', 'forms', ['question_answer'], ['id'])
        batch_op.drop_column('form_id')

    # ### end Alembic commands ###
